version: 1.0

services:
  - name: service1
    maxRPS: 
      rps: 10000
      cpu: // these values will be updated by the prediction model
      memory:
    minRPS:
      rps: 100
      cpu:
      memory:

  - name: service2
    maxRPS:
      rps: 50000
      cpu:
      memory:
    minRPS:
      rps: 100
      cpu:
      memory:

resources:
  pods:
    maxCPU: 100m
    maxMemory: 200Mi


