resources:
  pods:
    maxCPU: 0.4
    maxMemory: 0.6
  privateResources:
    nodeCount: 3
services:
- helmChartPath: ~/helm_charts/prime-chart
  minRPS:
    pods: 5
    rps: 100
  name: prime
  private: false
- helmChartPath: ~/helm_charts/auth-chart
  minRPS:
    pods: 1
    rps: 100
  name: auth
  private: false
version: 1.0
