version: 1.0

services:
  - name: service1
    private: False
    maxRPS: 
      rps: 10000
      cpu: // these values will be updated by the prediction model
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 2
    helmChartPath: "~/helm_charts/auth-chart"

  - name: service2
    private: False
    maxRPS:
      rps: 50000
      cpu:
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 1
    helmChartPath: "~/helm_charts/converter-chart"

  - name: service3
    private: True
    maxRPS:
      rps: 50000
      cpu:
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 6
    helmChartPath: "~/helm_charts/converter-chart"

  - name: service4
    private: True
    maxRPS:
      rps: 50000
      cpu:
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 6
    helmChartPath: "~/helm_charts/auth-chart"

resources:
  pods:
    maxCPU: 0.4
    maxMemory: 0.6
  privateResources:
    nodeCount: 3
services:
- helmChartPath: ~/helm_charts/converter-chart
  maxRPS:
    cpu: null
    memory: null
    pods: null
    rps: 50000
  minRPS:
    cpu: null
    memory: null
    pods: 1
    rps: 100
  name: service2
  private: false
- maxRPS:
    cpu: null
    memory: null
    pods: null
    rps: 50000
  minRPS:
    cpu: null
    memory: null
    pods: 6
    rps: 100
  name: service3
  private: true
- maxRPS:
    cpu: null
    memory: null
    pods: null
    rps: 50000
  minRPS:
    cpu: null
    memory: null
    pods: 6
    rps: 100
  name: service4
  private: true
- helmChartPath: ~/helm_charts/auth-chart
  minRPS:
    pods: 2
    rps: 100
  name: prime
  private: false
version: 1.0
