resources:
  pods:
    maxCPU: 0.4
    maxMemory: 0.6
  privateResources:
    nodeCount: 3
services:
- helmChartPath: ~/helm_charts/auth-chart
  maxRPS:
    cpu: // these values will be updated by the prediction model
    memory: null
    pods: null
    rps: 200
  minRPS:
    cpu: null
    memory: null
    pods: 2
    rps: 100
  name: prime
  private: false
- helmChartPath: ~/helm_charts/converter-chart
  maxRPS:
    cpu: null
    memory: null
    pods: null
    rps: 50000
  minRPS:
    cpu: null
    memory: null
    pods: 1
    rps: 100
  name: service2
  private: false
- maxRPS:
    cpu: null
    memory: null
    pods: null
    rps: 50000
  minRPS:
    cpu: null
    memory: null
    pods: 6
    rps: 100
  name: service3
  private: true
- maxRPS:
    cpu: null
    memory: null
    pods: null
    rps: 50000
  minRPS:
    cpu: null
    memory: null
    pods: 6
    rps: 100
  name: service4
  private: true
version: 1.0
