version: 1.0

services:
  - name: service1
    private: False
    maxRPS: 
      rps: 10000
      cpu: // these values will be updated by the prediction model
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 2
    helmChartPath: "~/helm_charts/auth-chart"

  - name: service2
    private: False
    maxRPS:
      rps: 50000
      cpu:
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 1
    helmChartPath: "~/helm_charts/converter-chart"

  - name: service3
    private: True
    maxRPS:
      rps: 50000
      cpu:
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 6
    helmChartPath: "~/helm_charts/converter-chart"

  - name: service4
    private: True
    maxRPS:
      rps: 50000
      cpu:
      memory:
      pods:
    minRPS:
      rps: 100
      cpu:
      memory:
      pods: 6
    helmChartPath: "~/helm_charts/auth-chart"

resources:
  privateResources:
    nodeCount: 3
  pods:
    maxCPU: 0.4
    maxMemory: 0.6


