version: 1.0

services:
  - name: prime
    maxRPS: 10000
    minRPS: 40
    private: False
    helmChartPath: /home/ksr/Documents/FYP/dev/microservices-python/src/prime/prime-chart

  - name: auth
    maxRPS: 50000
    minRPS: 100
    private: False
    helmChartPath: /home/ksr/Documents/FYP/dev/microservices-python/src/auth/auth-chart

privateResources:
      nodeCount: 10
      nodeCPU: 4
      nodeMemory: 8
