version: 1.0

services:
  - name: service1_auth
    maxRPS: 10000
    minRPS: 100
    private: False
    helmChartPath: /home/pasindu/projects/fyp/microservices/microservices-python/src/auth/auth-chart

  - name: service2_converter
    maxRPS: 50000
    minRPS: 100
    private: True
    helmChartPath: "/home/pasindu/projects/fyp/microservices/microservices-python/src/converter/converter-chart"

  - name: service3_converter
    maxRPS: 50000
    minRPS: 100
    private: False
    helmChartPath: "/home/pasindu/projects/fyp/microservices/microservices-python/src/converter/converter-chart"

  - name: service4_auth
    maxRPS: 50000
    minRPS: 100
    private: False
    helmChartPath: "/home/pasindu/projects/fyp/microservices/microservices-python/src/auth/auth-chart"

privateResources:
      nodeCount: 10
      nodeCPU: 4
      nodeMemory: 8

    

