version: 1.0

services:
  - name: prime
    maxRPS: 10000
    minRPS: 100
    private: False
    helmChartPath: /home/pasindu/projects/fyp/microservices/microservices-python/src/auth/auth-chart

  - name: service2
    maxRPS: 50000
    minRPS: 100
    private: True
    helmChartPath: /home/pasindu/projects/fyp/microservices/microservices-python/src/converter/converter-chart

privateResources:
      nodeCount: 10
      nodeCPU: 4
      nodeMemory: 8